const productsData = [
    {
        id: 1,
        img: "/images/c.jpg",
        rating: "★★★★",
        title: "C Book",
        price: 1000,
        quantity: 1,
    },
    {
        id: 2,
        img: "/images/c++.jpg",
        rating: "★★★★★",
        title: "C++ Book",
        price: 2000,
        quantity: 1,
    },
    {
        id: 3,
        img: "/images/css.jpg",
        rating: "★★★★",
        title: "CSS Book",
        price: 3000,
        quantity: 1,
    },
    {
        id: 4,
        img: "/images/dsa.jpg",
        rating: "★★★★★",
        title: "DSA Book",
        price: 4000,
        quantity: 1,
    },
    {
        id: 5,
        img: "/images/html.png",
        rating: "★★★★",
        title: "HTML Book",
        price: 5000,
        quantity: 1,
    },
    {
        id: 6,
        img: "/images/java.jpg",
        rating: "★★★★★",
        title: "Java Book",
        price: 6000,
        quantity: 1,
    },
    {
        id: 7,
        img: "/images/javascript.jpg",
        rating: "★★★★",
        title: "JavaScript Book",
        price: 7000,
        quantity: 1,
    },
    {
        id: 8,
        img: "/images/mongo.jpg",
        rating: "★★★★",
        title: "MongoDB Book",
        price: 8000,
        quantity: 1,
    },
    {
        id: 9,
        img: "/images/power.jpg",
        rating: "★★★★",
        title: "Power BI",
        price: 9000,
        quantity: 1,
    },
    {
        id: 10,
        img: "/images/python.jpg",
        rating: "★★★★",
        title: "Python Book",
        price: 10000,
        quantity: 1,
    },
    {
        id: 11,
        img: "/images/reactjs.jpg",
        rating: "★★★★",
        title: "React Book ",
        price: 11000,
        quantity: 1,
    },
    {
        id: 12,
        img: "/images/sql.jpg",
        rating: "★★★★",
        title: "SQL Book",
        price: 12000,
        quantity: 1,
    }
];

export default productsData;